# filepath: ./backend/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY ./data/csvs/Relatorio_cadop.csv /data/csvs/Relatorio_cadop.csv
COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]